<<<<<<< HEAD
# Generated by Django 3.2 on 2021-04-15 12:24
=======
# Generated by Django 3.1.7 on 2021-04-15 09:34
>>>>>>> 68cabe46be1757c39b6dec93ab5fb38ddea2ec90

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
<<<<<<< HEAD
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
=======
>>>>>>> 68cabe46be1757c39b6dec93ab5fb38ddea2ec90
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='1', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipMode', models.CharField(blank=True, max_length=50, null=True)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('sales', models.FloatField(blank=True, default='0', null=True)),
                ('discount', models.FloatField(blank=True, default='0', null=True)),
                ('profit', models.FloatField(blank=True, default='0', null=True)),
                ('shipping_cost', models.FloatField(blank=True, default='0', null=True)),
                ('order_priority', models.IntegerField(blank=True, default='0', null=True)),
                ('shipday', models.IntegerField(blank=True, null=True)),
                ('shipmonth', models.IntegerField(blank=True, null=True)),
                ('shipyear', models.IntegerField(blank=True, null=True)),
                ('orderday', models.IntegerField(blank=True, null=True)),
                ('ordermonth', models.IntegerField(blank=True, null=True)),
                ('orderyear', models.IntegerField(blank=True, null=True)),
                ('prod_price', models.FloatField(blank=True, default='0', null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=10, unique=True)),
                ('prod_price', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
=======
>>>>>>> 68cabe46be1757c39b6dec93ab5fb38ddea2ec90
    ]
