# Generated by Django 3.1.7 on 2021-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Electronics'), ('', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Stationary', 'Stationary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
